# 实验名称
experiment: "CAN"

# 随机种子
seed: 20211024

# 训练参数
epochs: 1
batch_size: 8
workers: 0
train_parts: 1
valid_parts: 1
valid_start: 0
save_start: 0

optimizer: Adadelta
lr: 1
lr_decay: cosine
step_ratio: 10
step_decay: 5
eps: 1e-6
weight_decay: 1e-4
beta: 0.9

dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# 训练数据
# train_image_path: 'datasets/CROHME/train_images.pkl'
# train_label_path: 'datasets/CROHME/train_labels.txt'
train_file_path: 
  - 'datasets/MyDataset/train_files/batch_0.npy'
  - 'datasets/MyDataset/train_files/batch_1.npy'
  - 'datasets/MyDataset/train_files/batch_2.npy'
  - 'datasets/MyDataset/train_files/batch_3.npy'
  - 'datasets/MyDataset/train_files/batch_4.npy'
  - 'datasets/MyDataset/train_files/batch_5.npy'
  - 'datasets/MyDataset/train_files/batch_6.npy'
  - 'datasets/MyDataset/train_files/batch_7.npy'
  - 'datasets/MyDataset/train_files/batch_8.npy'

# eval_image_path: 'datasets/CROHME/14_test_images.pkl'
# eval_label_path: 'datasets/CROHME/14_test_labels.txt'
eval_file_path: 
  - 'datasets/MyDataset/eval_files/batch_9.npy'
  - 'datasets/MyDataset/eval_files/batch_10.npy'
  
word_path: 'datasets/MyDataset/vocab.txt'

# collate_fn
collate_fn: collate_fn

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

encoder:
  input_channel: 3
  out_channel: 684

decoder:
  net: AttDecoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256

counting_decoder:
  in_channel: 684
  out_channel: 415

attention:
  attention_dim: 512
  word_conv_kernel: 1

attention_map_vis_path: 'vis/attention_map'
counting_map_vis_path: 'vis/counting_map'

whiten_type: None
max_step: 256

optimizer_save: False
finetune: False
checkpoint_dir: 'checkpoints'
checkpoint: ""
log_dir: 'logs'
